version: '3'
services:
  dashboard:
    build: ./dashboard/
    ports:
      - "3000:3000"
  m1:
    build: ./machine1/
    ports:
      - "3001:3000"
    depends_on:
      - etcd
  m2:
    build: ./machine2/
    ports:
      - "3002:3000"
    depends_on:
      - etcd
  etcdbrowser:
    image: woosley/etcd-browser
    ports:
      - "8080:8080"
    volumes:
      - ./etcd-browser/config.yaml:/app/config.yaml
    depends_on:
      - etcd
  etcd:
    image: quay.io/coreos/etcd
    command:
      - /usr/local/bin/etcd
      - "-advertise-client-urls=http://0.0.0.0:2379"
      - "-listen-client-urls=http://0.0.0.0:2379"
    ports:
      - "2379:2379"
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # these variables are unused by this service.
      # They are metadata required, by the letsencrypt-companion
      - VIRTUAL_HOST
      - VIRTUAL_PORT
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL
  sut:
    build: 
      context: ./CI_Tests
      dockerfile: Dockerfile.test
    links:
      - dashboard
    depends_on:
      - dashboard

